version = 0.1

[default.global.parameters]
stack_name = "gani-timeblock"
resolve_s3 = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = false

[default.sync.parameters]
watch = true
skip_deploy_sync = true
dependency_layer = false
